version: '3'

services:
  web:
    build: ./agilemusic
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/agileMusicDb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
