name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t app ./agilemusic

    - name: Run Docker Container
      run: docker run -d --name app -p 3000:3000 app

    - name: Wait for Container to be Ready
      run: sleep 10

    - name: Execute Tests If Present
      run: docker exec app npm test
